export { default as Dashboard } from './components/dashboard/Dashboard'
export { default as IncomePage } from './components/income/IncomePage'
export { default as ExpensesPage } from './components/expenses/ExpensesPage'
export { default as SavingsPage } from './components/savings/SavingsPage'
export { default as InvestmentsPage } from './components/investments/InvestmentsPage'
export { default as BudgetsPage } from './components/budgets/BudgetsPage'
export { default as AnalyticsPage } from './components/analytics/AnalyticsPage'
export { default as InsightsPage } from './components/insights/InsightsPage'
export { default as MarketPage } from './components/market/MarketPage'
export { default as SettingsPage } from './components/settings/SettingsPage'
export { default as ProfilePage } from './components/profile/ProfilePage'
export { default as LoginPage } from './components/auth/LoginPage'
export { default as RegisterPage } from './components/auth/RegisterPage'
export { default as NotFoundPage } from './components/NotFoundPage'

export { default as AuthLayout } from './layouts/AuthLayout'
export { default as DashboardLayout } from './layouts/DashboardLayout'
